{"name": "Добавление товара в корзину", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (351, 1028)\n  (Session info: chrome=127.0.6533.88)\nStacktrace:\n#0 0x60e3dd41e6ba <unknown>\n#1 0x60e3dd0ee730 <unknown>\n#2 0x60e3dd144a96 <unknown>\n#3 0x60e3dd1429ad <unknown>\n#4 0x60e3dd140447 <unknown>\n#5 0x60e3dd13f30e <unknown>\n#6 0x60e3dd132d66 <unknown>\n#7 0x60e3dd160a52 <unknown>\n#8 0x60e3dd132719 <unknown>\n#9 0x60e3dd160c1e <unknown>\n#10 0x60e3dd17f1ca <unknown>\n#11 0x60e3dd1607f3 <unknown>\n#12 0x60e3dd130ec9 <unknown>\n#13 0x60e3dd13191e <unknown>\n#14 0x60e3dd3e49eb <unknown>\n#15 0x60e3dd3e8972 <unknown>\n#16 0x60e3dd3d1e15 <unknown>\n#17 0x60e3dd3e9502 <unknown>\n#18 0x60e3dd3b6d2f <unknown>\n#19 0x60e3dd40d578 <unknown>\n#20 0x60e3dd40d750 <unknown>\n#21 0x60e3dd41d48c <unknown>\n#22 0x771c6a414ac3 <unknown>", "trace": "browser = <selenium.webdriver.remote.webdriver.WebDriver (session=\"d0e47f447c98e9d08e7a766aab8d5964\")>, base_url = 'http://10.0.2.15:8081'\n\n    @allure.title(\"Добавление товара в корзину\")\n    def test_add_to_cart(browser, base_url):\n        home_page = HomePage(browser)\n        home_page.open(base_url)\n        home_page.scroll_down()\n>       home_page.add_product_to_cart()\n\ntests/test_start.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_objects/home_page.py:25: in add_product_to_cart\n    self.get_element(self.LISTING_CART_BUTTON).click()\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py:94: in click\n    self._execute(Command.CLICK_ELEMENT)\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py:395: in _execute\n    return self._parent.execute(command, params)\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7392518bc470>\nresponse = {'status': 400, 'value': '{\"value\":{\"error\":\"element click intercepted\",\"message\":\"element click intercepted: Element ...\\\\n#20 0x60e3dd40d750 \\\\u003Cunknown>\\\\n#21 0x60e3dd41d48c \\\\u003Cunknown>\\\\n#22 0x771c6a414ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (351, 1028)\nE         (Session info: chrome=127.0.6533.88)\nE       Stacktrace:\nE       #0 0x60e3dd41e6ba <unknown>\nE       #1 0x60e3dd0ee730 <unknown>\nE       #2 0x60e3dd144a96 <unknown>\nE       #3 0x60e3dd1429ad <unknown>\nE       #4 0x60e3dd140447 <unknown>\nE       #5 0x60e3dd13f30e <unknown>\nE       #6 0x60e3dd132d66 <unknown>\nE       #7 0x60e3dd160a52 <unknown>\nE       #8 0x60e3dd132719 <unknown>\nE       #9 0x60e3dd160c1e <unknown>\nE       #10 0x60e3dd17f1ca <unknown>\nE       #11 0x60e3dd1607f3 <unknown>\nE       #12 0x60e3dd130ec9 <unknown>\nE       #13 0x60e3dd13191e <unknown>\nE       #14 0x60e3dd3e49eb <unknown>\nE       #15 0x60e3dd3e8972 <unknown>\nE       #16 0x60e3dd3d1e15 <unknown>\nE       #17 0x60e3dd3e9502 <unknown>\nE       #18 0x60e3dd3b6d2f <unknown>\nE       #19 0x60e3dd40d578 <unknown>\nE       #20 0x60e3dd40d750 <unknown>\nE       #21 0x60e3dd41d48c <unknown>\nE       #22 0x771c6a414ac3 <unknown>\n\nvenv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: ElementClickInterceptedException"}, "steps": [{"name": "Открываю http://10.0.2.15:8081", "status": "passed", "start": 1725286398426, "stop": 1725286399676}, {"name": "Скроллю страницу вниз", "status": "passed", "start": 1725286399676, "stop": 1725286399836}, {"name": "Добавляю товар в корзину", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (351, 1028)\n  (Session info: chrome=127.0.6533.88)\nStacktrace:\n#0 0x60e3dd41e6ba <unknown>\n#1 0x60e3dd0ee730 <unknown>\n#2 0x60e3dd144a96 <unknown>\n#3 0x60e3dd1429ad <unknown>\n#4 0x60e3dd140447 <unknown>\n#5 0x60e3dd13f30e <unknown>\n#6 0x60e3dd132d66 <unknown>\n#7 0x60e3dd160a52 <unknown>\n#8 0x60e3dd132719 <unknown>\n#9 0x60e3dd160c1e <unknown>\n#10 0x60e3dd17f1ca <unknown>\n#11 0x60e3dd1607f3 <unknown>\n#12 0x60e3dd130ec9 <unknown>\n#13 0x60e3dd13191e <unknown>\n#14 0x60e3dd3e49eb <unknown>\n#15 0x60e3dd3e8972 <unknown>\n#16 0x60e3dd3d1e15 <unknown>\n#17 0x60e3dd3e9502 <unknown>\n#18 0x60e3dd3b6d2f <unknown>\n#19 0x60e3dd40d578 <unknown>\n#20 0x60e3dd40d750 <unknown>\n#21 0x60e3dd41d48c <unknown>\n#22 0x771c6a414ac3 <unknown>\n\n", "trace": "  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/page_objects/home_page.py\", line 25, in add_product_to_cart\n    self.get_element(self.LISTING_CART_BUTTON).click()\n  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/fuenukkusu2501/PycharmProjects/OTUS_selenium_UI/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725286399836, "stop": 1725286401013}], "start": 1725286398426, "stop": 1725286401023, "uuid": "a8461b95-ae9c-4d9e-b998-4c315d6dd172", "historyId": "2987328dc021ab097458a9c10fd9e829", "testCaseId": "2987328dc021ab097458a9c10fd9e829", "fullName": "tests.test_start#test_add_to_cart", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_start"}, {"name": "host", "value": "fuenukkusu2501-VirtualBox"}, {"name": "thread", "value": "198144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_start"}]}