{
  "uid" : "823ee2869ed4e8e9",
  "name" : "Добавление товара в корзину",
  "fullName" : "tests.test_start#test_add_to_cart",
  "historyId" : "2987328dc021ab097458a9c10fd9e829",
  "time" : {
    "start" : 1720461022454,
    "stop" : 1720461022871,
    "duration" : 417
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=123.0.6312.105)\nStacktrace:\n#0 0x639a3eb84863 <unknown>\n#1 0x639a3e87a8c6 <unknown>\n#2 0x639a3e8729f3 <unknown>\n#3 0x639a3e862b2b <unknown>\n#4 0x639a3e8640c2 <unknown>\n#5 0x639a3e862e4c <unknown>\n#6 0x639a3e862638 <unknown>\n#7 0x639a3e862485 <unknown>\n#8 0x639a3e860516 <unknown>\n#9 0x639a3e860a2a <unknown>\n#10 0x639a3e87d24e <unknown>\n#11 0x639a3e9067c5 <unknown>\n#12 0x639a3e8e75a2 <unknown>\n#13 0x639a3e905c19 <unknown>\n#14 0x639a3e8e7343 <unknown>\n#15 0x639a3e8b8593 <unknown>\n#16 0x639a3e8b8f5e <unknown>\n#17 0x639a3eb4884b <unknown>\n#18 0x639a3eb4c7a5 <unknown>\n#19 0x639a3eb36571 <unknown>\n#20 0x639a3eb4d332 <unknown>\n#21 0x639a3eb1b87f <unknown>\n#22 0x639a3eb73728 <unknown>\n#23 0x639a3eb738fb <unknown>\n#24 0x639a3eb839b4 <unknown>\n#25 0x7f5ca0294ac3 <unknown>",
  "statusTrace" : "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"07674a6a00c1a54e55c4db37fbd4cede\")>, base_url = 'http://10.0.2.15:8081'\n\n    @allure.title(\"Добавление товара в корзину\")\n    def test_add_to_cart(browser, base_url):\n        home_page = HomePage(browser)\n>       home_page.open(base_url)\n\ntests/test_start.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_objects/home_page.py:13: in open\n    self.browser.get(url)\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x74f15f9ba170>, response = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x639a3eb738fb \\\\u003Cunknown>\\\\n#24 0x639a3eb839b4 \\\\u003Cunknown>\\\\n#25 0x7f5ca0294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=123.0.6312.105)\nE       Stacktrace:\nE       #0 0x639a3eb84863 <unknown>\nE       #1 0x639a3e87a8c6 <unknown>\nE       #2 0x639a3e8729f3 <unknown>\nE       #3 0x639a3e862b2b <unknown>\nE       #4 0x639a3e8640c2 <unknown>\nE       #5 0x639a3e862e4c <unknown>\nE       #6 0x639a3e862638 <unknown>\nE       #7 0x639a3e862485 <unknown>\nE       #8 0x639a3e860516 <unknown>\nE       #9 0x639a3e860a2a <unknown>\nE       #10 0x639a3e87d24e <unknown>\nE       #11 0x639a3e9067c5 <unknown>\nE       #12 0x639a3e8e75a2 <unknown>\nE       #13 0x639a3e905c19 <unknown>\nE       #14 0x639a3e8e7343 <unknown>\nE       #15 0x639a3e8b8593 <unknown>\nE       #16 0x639a3e8b8f5e <unknown>\nE       #17 0x639a3eb4884b <unknown>\nE       #18 0x639a3eb4c7a5 <unknown>\nE       #19 0x639a3eb36571 <unknown>\nE       #20 0x639a3eb4d332 <unknown>\nE       #21 0x639a3eb1b87f <unknown>\nE       #22 0x639a3eb73728 <unknown>\nE       #23 0x639a3eb738fb <unknown>\nE       #24 0x639a3eb839b4 <unknown>\nE       #25 0x7f5ca0294ac3 <unknown>\n\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "browser",
    "time" : {
      "start" : 1720461018390,
      "stop" : 1720461022453,
      "duration" : 4063
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "c5579b221c994314",
      "name" : "07674a6a00c1a54e55c4db37fbd4cede",
      "source" : "c5579b221c994314.json",
      "type" : "application/json",
      "size" : 965
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "base_url",
    "time" : {
      "start" : 1720461022454,
      "stop" : 1720461022454,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=123.0.6312.105)\nStacktrace:\n#0 0x639a3eb84863 <unknown>\n#1 0x639a3e87a8c6 <unknown>\n#2 0x639a3e8729f3 <unknown>\n#3 0x639a3e862b2b <unknown>\n#4 0x639a3e8640c2 <unknown>\n#5 0x639a3e862e4c <unknown>\n#6 0x639a3e862638 <unknown>\n#7 0x639a3e862485 <unknown>\n#8 0x639a3e860516 <unknown>\n#9 0x639a3e860a2a <unknown>\n#10 0x639a3e87d24e <unknown>\n#11 0x639a3e9067c5 <unknown>\n#12 0x639a3e8e75a2 <unknown>\n#13 0x639a3e905c19 <unknown>\n#14 0x639a3e8e7343 <unknown>\n#15 0x639a3e8b8593 <unknown>\n#16 0x639a3e8b8f5e <unknown>\n#17 0x639a3eb4884b <unknown>\n#18 0x639a3eb4c7a5 <unknown>\n#19 0x639a3eb36571 <unknown>\n#20 0x639a3eb4d332 <unknown>\n#21 0x639a3eb1b87f <unknown>\n#22 0x639a3eb73728 <unknown>\n#23 0x639a3eb738fb <unknown>\n#24 0x639a3eb839b4 <unknown>\n#25 0x7f5ca0294ac3 <unknown>",
    "statusTrace" : "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"07674a6a00c1a54e55c4db37fbd4cede\")>, base_url = 'http://10.0.2.15:8081'\n\n    @allure.title(\"Добавление товара в корзину\")\n    def test_add_to_cart(browser, base_url):\n        home_page = HomePage(browser)\n>       home_page.open(base_url)\n\ntests/test_start.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_objects/home_page.py:13: in open\n    self.browser.get(url)\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x74f15f9ba170>, response = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x639a3eb738fb \\\\u003Cunknown>\\\\n#24 0x639a3eb839b4 \\\\u003Cunknown>\\\\n#25 0x7f5ca0294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=123.0.6312.105)\nE       Stacktrace:\nE       #0 0x639a3eb84863 <unknown>\nE       #1 0x639a3e87a8c6 <unknown>\nE       #2 0x639a3e8729f3 <unknown>\nE       #3 0x639a3e862b2b <unknown>\nE       #4 0x639a3e8640c2 <unknown>\nE       #5 0x639a3e862e4c <unknown>\nE       #6 0x639a3e862638 <unknown>\nE       #7 0x639a3e862485 <unknown>\nE       #8 0x639a3e860516 <unknown>\nE       #9 0x639a3e860a2a <unknown>\nE       #10 0x639a3e87d24e <unknown>\nE       #11 0x639a3e9067c5 <unknown>\nE       #12 0x639a3e8e75a2 <unknown>\nE       #13 0x639a3e905c19 <unknown>\nE       #14 0x639a3e8e7343 <unknown>\nE       #15 0x639a3e8b8593 <unknown>\nE       #16 0x639a3e8b8f5e <unknown>\nE       #17 0x639a3eb4884b <unknown>\nE       #18 0x639a3eb4c7a5 <unknown>\nE       #19 0x639a3eb36571 <unknown>\nE       #20 0x639a3eb4d332 <unknown>\nE       #21 0x639a3eb1b87f <unknown>\nE       #22 0x639a3eb73728 <unknown>\nE       #23 0x639a3eb738fb <unknown>\nE       #24 0x639a3eb839b4 <unknown>\nE       #25 0x7f5ca0294ac3 <unknown>\n\n../../../.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
    "steps" : [ {
      "name" : "Открываю http://10.0.2.15:8081",
      "time" : {
        "start" : 1720461022454,
        "stop" : 1720461022869,
        "duration" : 415
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=123.0.6312.105)\nStacktrace:\n#0 0x639a3eb84863 <unknown>\n#1 0x639a3e87a8c6 <unknown>\n#2 0x639a3e8729f3 <unknown>\n#3 0x639a3e862b2b <unknown>\n#4 0x639a3e8640c2 <unknown>\n#5 0x639a3e862e4c <unknown>\n#6 0x639a3e862638 <unknown>\n#7 0x639a3e862485 <unknown>\n#8 0x639a3e860516 <unknown>\n#9 0x639a3e860a2a <unknown>\n#10 0x639a3e87d24e <unknown>\n#11 0x639a3e9067c5 <unknown>\n#12 0x639a3e8e75a2 <unknown>\n#13 0x639a3e905c19 <unknown>\n#14 0x639a3e8e7343 <unknown>\n#15 0x639a3e8b8593 <unknown>\n#16 0x639a3e8b8f5e <unknown>\n#17 0x639a3eb4884b <unknown>\n#18 0x639a3eb4c7a5 <unknown>\n#19 0x639a3eb36571 <unknown>\n#20 0x639a3eb4d332 <unknown>\n#21 0x639a3eb1b87f <unknown>\n#22 0x639a3eb73728 <unknown>\n#23 0x639a3eb738fb <unknown>\n#24 0x639a3eb839b4 <unknown>\n#25 0x7f5ca0294ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/home/fuenukkusu2501/Develop/tmp/OTUS_selenium_UI/page_objects/home_page.py\", line 13, in open\n    self.browser.get(url)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/home/fuenukkusu2501/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "browser::0",
    "time" : {
      "start" : 1720461022976,
      "stop" : 1720461023415,
      "duration" : 439
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "d50e6c08da689d02",
      "name" : "failure_screenshot",
      "source" : "d50e6c08da689d02.png",
      "type" : "image/png",
      "size" : 32941
    }, {
      "uid" : "511bfd10eedd2013",
      "name" : "page_source",
      "source" : "511bfd10eedd2013.html",
      "type" : "text/html",
      "size" : 240378
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_start"
  }, {
    "name" : "host",
    "value" : "Ubuntu"
  }, {
    "name" : "thread",
    "value" : "14041-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_start"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "823ee2869ed4e8e9.json",
  "parameterValues" : [ ]
}